DROP TABLE IF EXISTS CONTACT;

CREATE TABLE CONTACT (
    ID INT NOT NULL AUTO_INCREMENT
  , FIRST_NAME VARCHAR(60) NOT NULL
  , LAST_NAME VARCHAR(40) NOT NULL
  , BIRTH_DATE DATE
  , DESCRIPTION VARCHAR(2000)
  , PHOTO BLOB
  , VERSION INT NOT NULL DEFAULT 0
  , UNIQUE UQ_CONTACT_1 (FIRST_NAME, LAST_NAME)
  , PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER (
    ID INT NOT NULL AUTO_INCREMENT
  , FIRST_NAME VARCHAR(60) NOT NULL
  , LAST_NAME VARCHAR(40) NOT NULL
  , VERSION INT NOT NULL DEFAULT 0
  , UNIQUE UQ_CUSTOMER_1 (FIRST_NAME, LAST_NAME)
  , PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS ACCOUNT;
CREATE TABLE ACCOUNT (
    ID INT NOT NULL AUTO_INCREMENT
  , CUSTOMER_ID INT NOT NULL
  , EXPIRY_DATE DATE
  , VERSION INT NOT NULL DEFAULT 0
  , PRIMARY KEY (ID)
  , FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID) ON DELETE CASCADE
);